### ISSUE TITLE
Error occurred when executing DownloadAndLoadMimicMotionModel - CUDA Setup failed despite GPU being available:  python -m bitsandbytes

### ISSUE THREAD

**Issue by schneegecko** [bitsandbytes-foundation/bitsandbytes#1277]
### System Info

Windows 10
python 3.10.11
Lenovo Laptop, Intel CPU with 4090 16gb rtx graphics card

### Reproduction

running comfyui samlple workfow of [MimicmotionModule ](https://github.com/tencent/MimicMotion)

### Expected behavior

Running of the workflow MimicMotion Module.
-------
I've tried so far: uninstall bitsandbytes via pip[, reinstall bitsandbytes v0.41.2](https://github.com/bitsandbytes-foundation/bitsandbytes/issues/741?utm_source=pocket_saves)

Did not work, so I reinstalled bitsandbytes 0.43.1 -> same error message

---------------------

Full error message:

Loading model from: H:\sd\ComfyUI_windows_portable\ComfyUI\models\mimicmotion\MimicMotionMergedUnet_1-0-fp16.safetensors
Loading UNET
Loading VAE
Loading IMAGE_ENCODER
Loading POSE_NET
===================================BUG REPORT===================================

The following directories listed in your path were found to be non-existent: {WindowsPath('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAbOE8jecGMkqq+pL5c9J9rQQAAAACAAAAAAAQZgAAAAEAACAAAABj+AuPKeEXxEk0wAcS5owqqdI9cOOVmOpku9t/cv0j4gAAAAAOgAAAAAIAACAAAABkWAM5dw6jN480b0Oajd7b55rqRlV4jeBHicn4uqgELWAAAAAAdac5uyVzK3T5foQhbH7eU3bmwoQkE/vcuOGxamyPbIwmP3bRgb56yBszUP+lpW/tisixKHwMyHOPFXCj5h/+0aA+sxrg/dOwAiGZHkf6mEfyalWJ0BH5nH9fx0s4RnFAAAAA/6+7c1hj72ub7iDdEzzb35Gz/ni7Pcf3AHqsgDgrVRbjBXxOGLBduYM3BWXAu1zYPY0WiaUzr7/ZEWtc2SptCw==')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
!!! Exception during processing!!!
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

    python -m bitsandbytes

    Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
    to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
    and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Traceback (most recent call last):
File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 143, in loadmodel
pipeline = MimicMotionPipeline(
^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 111, in init
self.register_modules(
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 159, in register_modules
library, class_name = fetch_class_library_tuple(module)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 733, in fetch_class_library_tuple
not_compiled_module = unwrap_model(module)
^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 236, in unwrap_model
from peft import PeftModel
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft_init.py", line 22, in
from .auto import (
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 31, in
from .config import PeftConfig
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\config.py", line 23, in
from .utils import CONFIG_NAME, PeftType, TaskType
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils_init.py", line 21, in
from .loftq_utils import replace_lora_weights_loftq
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils\loftq_utils.py", line 35, in
import bitsandbytes as bnb
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes_init.py", line 6, in
from . import cuda_setup, utils, research
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research_init.py", line 1, in
from . import nn
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research\nn_init_.py", line 1, in
from .modules import LinearFP8Mixed, LinearFP8Global
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in
from bitsandbytes.optim import GlobalOptimManager
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\optim_init_.py", line 6, in
from bitsandbytes.cextension import COMPILED_WITH_CUDA
File "H:\sd\ComfyUI_windows_portable\python_embeded\Lib\site-packages\bitsandbytes\cextension.py", line 20, in
raise RuntimeError('''
RuntimeError:
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

    python -m bitsandbytes

    Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
    to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
    and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

and:

H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes>python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
CUDA specs: CUDASpecs(highest_compute_capability=(8, 9), cuda_version_string='118', cuda_version_tuple=(11, 8))
PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: (8, 9).
To manually override the PyTorch CUDA version please see: https://github.com/TimDettmers/bitsandbytes/blob/main/docs/source/nonpytorchcuda.mdx
The directory listed in your path is found to be non-existent: C:\WINDOWS\ConfigSetRoot
The directory listed in your path is found to be non-existent: \Users\gecko
The directory listed in your path is found to be non-existent: \GECKO-LEGION
CUDA SETUP: WARNING! CUDA runtime files not found in any environmental path.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking that the library is importable and CUDA is callable...
SUCCESS!
Installation was successful!

**Comment by hanetyb** [comment]
seem i meet the same issue by same mimicmotion plug, any adivce here.
![image](https://github.com/user-attachments/assets/b57e84ef-dcbd-49a6-bc05-7d62bf70b57b)

**Comment by TimDettmers** [comment]
Closing this issue. This was reported against bitsandbytes 0.41.2–0.43.1 on Windows, which was before official Windows support was added in v0.43.0. The old CUDA detection system also gave Linux-specific guidance (e.g. `libcudart.so`, `LD_LIBRARY_PATH`, `sudo ldconfig`) on Windows, which was not helpful. Both the Windows support and the library loading system have been completely overhauled in recent releases.

If you're still hitting problems on the **latest** bitsandbytes (v0.45+), please open a new issue with the output of `python -m bitsandbytes` and your environment details.
