### ISSUE TITLE
RuntimeError:         CUDA Setup failed despite GPU being available. Please run the following command to get more information:          python -m bitsandbytes          Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

### ISSUE THREAD

**Issue by senzawapoi** [bitsandbytes-foundation/bitsandbytes#1307]
### System Info

windows10 python:3.10.7 cuda:12.4 pytorch:2.4.0+cu124

### Reproduction

C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\matplotlib\projections\__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
bin C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\libbitsandbytes_cuda124.dll
False

===================================BUG REPORT===================================
C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py:174: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA SETUP: PyTorch settings found: CUDA_VERSION=124, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda124.dll. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.dll...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=124
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\modules\initialize.py", line 26, in imports
    from modules import paths, timer, import_hook, errors  # noqa: F401
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\modules\paths.py", line 60, in <module>
    import sgm  # noqa: F401
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\repositories\generative-models\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\repositories\generative-models\sgm\models\autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\repositories\generative-models\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "C:\Users\DELL\Desktop\stable-diffusion-webui\stable-diffusion-webui\repositories\generative-models\sgm\modules\encoders\modules.py", line 5, in <module>
    import kornia
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\kornia\__init__.py", line 11, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\kornia\x\__init__.py", line 2, in <module>
    from .trainer import Trainer
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\kornia\x\trainer.py", line 11, in <module>
    from accelerate import Accelerator
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

### Expected behavior

When I run stable-diffusion-webui, the following error occurs. Can anyone help me solve it? Thank you

**Comment by senzawapoi** [comment]
> 我也遇到了这个问题，我注意到你的 cude 是 12.4，所以我认为你可以尝试运行这个“pip install bitsandbytes==0.43.1”。我认为它有效。

ty

**Comment by matthewdouglas** [comment]
We noticed that there has been no recent activity on this issue. As a result, we will be closing it for now. If you continue to experience this problem or have additional information to provide, please feel free to reopen the issue or create a new one.

Thank you for your understanding.
