### ISSUE TITLE
Runtime Error, cannot import name 'get_keys_to_not_convert' from 'transformers.integrations'

### ISSUE THREAD

**Issue by zeruiz99** [bitsandbytes-foundation/bitsandbytes#1309]
### System Info

**Error messages:**
```
Traceback (most recent call last):
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/data/miniconda3/envs/bab/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/integrations/bitsandbytes.py", line 13, in <module>
    import bitsandbytes as bnb
  File "/group/40064/neilzrzhang/quantilization/method/bitsandbytes.py", line 10, in <module>
    quantized_model = AutoModelForCausalLM.from_pretrained(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3827, in from_pretrained
    hf_quantizer.preprocess_model(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/quantizers/base.py", line 182, in preprocess_model
    return self._process_model_before_weight_loading(model, **kwargs)
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 260, in _process_model_before_weight_loading
    from ..integrations import get_keys_to_not_convert, replace_with_bnb_linear
ImportError: cannot import name 'get_keys_to_not_convert' from 'transformers.integrations' (/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/integrations/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/group/40064/neilzrzhang/quantilization/method/bitsandbytes.py", line 10, in <module>
    quantized_model = AutoModelForCausalLM.from_pretrained(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3827, in from_pretrained
    hf_quantizer.preprocess_model(
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/quantizers/base.py", line 182, in preprocess_model
    return self._process_model_before_weight_loading(model, **kwargs)
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 260, in _process_model_before_weight_loading
    from ..integrations import get_keys_to_not_convert, replace_with_bnb_linear
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):
cannot import name 'get_keys_to_not_convert' from 'transformers.integrations' (/data/miniconda3/envs/bab/lib/python3.10/site-packages/transformers/integrations/__init__.py)
```

### version
cuda 11.8 torch 2.2.1 torchvision 0.17.1 accelerate 0.33.0 scipy 1.14.0 transformers 4.44.0 bitsandbytes 0.43.3

### Reproduction

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

quantized_model = AutoModelForCausalLM.from_pretrained(
	model_name, device_map="auto", torch_dtype=torch.bfloat16, quantization_config=quantization_config)
tokenizer = AutoTokenizer.from_pretrained(model_name)
```

### Expected behavior

can any contributor to mention about the specific version i should use or any other packages i missed. seems like it might be a issue in transformers with bitsandbytes. i also tried transformers==4.43.1
could not solve it

**Comment by Titus-von-Koeller** [comment]
Dear @zeruiz99, this is indeed really strange. However this is quite clearly not caused by bitsanbytes, the error trace points very clearly only to Transformer code paths.

You mentioned version 4.44.0 and the methods exists there, [as you can see here](https://github.com/huggingface/transformers/blob/984bc11b0882ff1e5b34ba717ea357e069ceced9/src/transformers/integrations/bitsandbytes.py#L284).

This indeed seems like a bug, but it's not immediately aparrent to me what causes it. Please be so kind to copy the issue text and [re-open the issue on the Transformer repo](https://github.com/huggingface/transformers/issues/new/choose)!
