### ISSUE TITLE
CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by carlxc911** [bitsandbytes-foundation/bitsandbytes#1394]
### System Info

windows11
cuda 12.6
pytorch 12.4
bitsandbytes https://github.com/jllllll/bitsandbytes/tree/cmake_windows_0.41.1

### Reproduction

when I run Llama Factory webui, it was broken and says:

python -m bitsandbytes

  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('/ai_2024/anaconda_2024/envs/llama_factory/lib'), WindowsPath('D')}
D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\ai_2024\anaconda_2024\envs\llama_factory did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {WindowsPath('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAIJuRFahcnkO2doFI7Edl3QQAAAACAAAAAAAQZgAAAAEAACAAAAAvMB+1sCNAMgkDTO45Ql1LECshSbdZ3VzO68u5ocLNtwAAAAAOgAAAAAIAACAAAACEWHZHY8QUf/GSFmVXlR20lKemhfSpkmRscbXzejn412AAAABpDOYyx5EwP1ET92G05jCPrQiHe6wafgfu8LSimIi7fbHMuqhQy5urnS4/k9GC3NHtHuWCNIdHnizbADqHXorE4t+V/PaKmdweSh4YZJ95CK9gQvUEf6Klw3BE+QLxSo9AAAAAr9T6+8IyHE49cH7Ad5Kjznm8nJ9wJffU4n+3i0Cr568tSUFlwrWL152yFrSIjd5zNH2+HDDz8fSqEe1Fz98MPw==')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=124, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda124.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\ai_2024\anaconda_2024\envs\llama_factory\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

### Expected behavior

what should I do?

**Comment by jnt0rrente** [comment]
Same issue here, even though all required libcudart versions (more than one, for some reason?) are present in the path

**Comment by So-cean** [comment]
same here

**Comment by duyandeyaojiaying1018** [comment]
what is the solution same here

**Comment by flashbackpoductions** [comment]
seems not support cude 12.6 new version

**Comment by TimDettmers** [comment]
Closing this issue. This was reported using an unofficial Windows fork (`jllllll/bitsandbytes`) from before official Windows support was added in bitsandbytes v0.43.0. The old CUDA detection system also searched for Linux `.so` files on Windows and gave Linux-specific advice. Both Windows support and the library loading system have been completely overhauled in recent releases.

Please upgrade to the latest official bitsandbytes (`pip install bitsandbytes`). If you're still hitting problems on v0.45+, please open a new issue with the output of `python -m bitsandbytes` and your environment details.
