### ISSUE TITLE
[Windows] [Error] Compile from source

### ISSUE THREAD

**Issue by blap** [bitsandbytes-foundation/bitsandbytes#1398]
### System Info

cmake -DCOMPUTE_BACKEND=cuda -S .

```
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.41.34123.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring bitsandbytes (Backend: cuda)
-- NO_CUBLASLT := OFF
-- The CUDA compiler identification is NVIDIA 12.6.77
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include (found version "12.6.77")
-- CUDA Version: 126 (12.6.77)
-- CUDA Compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/bin/nvcc.exe
-- CUDA Capabilities Available: 50;52;53;60;61;62;70;72;75;80;86;87;89;90
-- CUDA Capabilities  Selected: 50;52;53;60;61;62;70;72;75;80;86;87;89;90
-- CUDA Targets: 50-real;52-real;53-real;60-real;61-real;62-real;70-real;72-real;75-real;80-real;86-real;87-real;89-real;90
-- CUDA NVCC Flags:  --allow-unsupported-compiler -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH --use_fast_math
-- Configuring done (8.7s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes
```

### Reproduction

cmake --build . --config Release

```

Versão do MSBuild 17.11.9+a69bbaaf5 para .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes/CMakeLists.txt
  Compiling CUDA source file csrc\ops.cu...

  (venv) C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program F
  iles\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64" -x cu -rdc=true  -IC:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc -IC:\
  Users\Admin\Desktop\bitsandbytes\bitsandbytes\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -I"C:\Program Files\NVIDIA GPU Computing T
  oolkit\CUDA\v12.6\include"     --keep-dir bitsandbytes\x64\Release -use_fast_math -maxrregcount=0   --machine 64 --compile -cudart static --allow-unsupported-compile
  r --generate-code=arch=compute_50,code=[sm_50] --generate-code=arch=compute_52,code=[sm_52] --generate-code=arch=compute_53,code=[sm_53] --generate-code=arch=compute
  _60,code=[sm_60] --generate-code=arch=compute_61,code=[sm_61] --generate-code=arch=compute_62,code=[sm_62] --generate-code=arch=compute_70,code=[sm_70] --generate-co
  de=arch=compute_72,code=[sm_72] --generate-code=arch=compute_75,code=[sm_75] --generate-code=arch=compute_80,code=[sm_80] --generate-code=arch=compute_86,code=[sm_86
  ] --generate-code=arch=compute_87,code=[sm_87] --generate-code=arch=compute_89,code=[sm_89] --generate-code=arch=compute_90,code=[compute_90,sm_90] -Xcompiler=-Ob2
   -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH -DNDEBUG -DBUILD_CUDA -D"CMAKE_INTDIR=\"Release\"" -Dbitsandbytes_EXPORTS -D_WINDLL -D_MBCS -DWIN32 -D_WINDOWS -DNDEBUG -
  DBUILD_CUDA -D"CMAKE_INTDIR=\"Release\"" -Dbitsandbytes_EXPORTS -Xcompiler "/EHsc /W1 /nologo /O2 /FS   /MD " -Xcompiler "/Fdbitsandbytes.dir\Release\vc143.pdb" -o b
  itsandbytes.dir\Release\ops.obj "C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu"
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\ops.cu(498): warning #177-D: variable "tilesize" was declared but never referenced [C:\Users\Admin\Desktop\bitsan
dbytes\bitsandbytes\bitsandbytes.vcxproj]
      int tilesize = 32*subtile_rows;
          ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

  ops.cu
  tmpxft_00002ddc_00000000-7_ops.compute_90.cudafe1.cpp
  Compiling CUDA source file csrc\kernels.cu...

  (venv) C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program F
  iles\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64" -x cu -rdc=true  -IC:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc -IC:\
  Users\Admin\Desktop\bitsandbytes\bitsandbytes\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -I"C:\Program Files\NVIDIA GPU Computing T
  oolkit\CUDA\v12.6\include"     --keep-dir bitsandbytes\x64\Release -use_fast_math -maxrregcount=0   --machine 64 --compile -cudart static --allow-unsupported-compile
  r --generate-code=arch=compute_50,code=[sm_50] --generate-code=arch=compute_52,code=[sm_52] --generate-code=arch=compute_53,code=[sm_53] --generate-code=arch=compute
  _60,code=[sm_60] --generate-code=arch=compute_61,code=[sm_61] --generate-code=arch=compute_62,code=[sm_62] --generate-code=arch=compute_70,code=[sm_70] --generate-co
  de=arch=compute_72,code=[sm_72] --generate-code=arch=compute_75,code=[sm_75] --generate-code=arch=compute_80,code=[sm_80] --generate-code=arch=compute_86,code=[sm_86
  ] --generate-code=arch=compute_87,code=[sm_87] --generate-code=arch=compute_89,code=[sm_89] --generate-code=arch=compute_90,code=[compute_90,sm_90] -Xcompiler=-Ob2
   -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH -DNDEBUG -DBUILD_CUDA -D"CMAKE_INTDIR=\"Release\"" -Dbitsandbytes_EXPORTS -D_WINDLL -D_MBCS -DWIN32 -D_WINDOWS -DNDEBUG -
  DBUILD_CUDA -D"CMAKE_INTDIR=\"Release\"" -Dbitsandbytes_EXPORTS -Xcompiler "/EHsc /W1 /nologo /O2 /FS   /MD " -Xcompiler "/Fdbitsandbytes.dir\Release\vc143.pdb" -o b
  itsandbytes.dir\Release\kernels.obj "C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu"
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\csrc\kernels.cu(23): warning #177-D: variable "nf4_data" was declared but never referenced [C:\Users\Admin\Desktop\bit
sandbytes\bitsandbytes\bitsandbytes.vcxproj]
    __declspec(__device__) static float nf4_data[16] = {-1.0, -0.6961928009986877, -0.5250730514526367, -0.39491748809814453, -0.28444138169288635, -0.1847734302282333
  4, -0.09105003625154495, 0.0, 0.07958029955625534, 0.16093020141124725, 0.24611230194568634, 0.33791524171829224, 0.44070982933044434, 0.5626170039176941, 0.72295683
  62236023, 1.0};
                                        ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored [C:\Users\Admin\Desktop\bitsandbytes
\bitsandbytes\bitsandbytes.vcxproj]
  kernels.cu
  tmpxft_00001b50_00000000-7_kernels.compute_90.cudafe1.cpp
  common.cpp
  cpu_ops.cpp
  pythonInterface.cpp
  Gerando Código...

  (venv) C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc.exe" -dlink  -o bitsandbytes.dir\Release\l
  ibbitsandbytes_cuda126.device-link.obj -Xcompiler "/EHsc /W1 /nologo /O2   /MD " -Xcompiler "/Fdbitsandbytes.dir\Release\vc143.pdb" -L"C:\Program Files\NVIDIA GPU Co
  mputing Toolkit\CUDA\v12.6\bin/crt" -L"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/lib/x64" -L"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/
  lib/x64/Release" -L"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\cudart.lib" "
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\cublas.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\cusparse.lib" "C:\Prog
  ram Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\cublasLt.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\nvJitLink.lib" cudadevrt.li
  b cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib -forward-unknown-to-host-com
  piler -Wno-deprecated-gpu-targets  --allow-unsupported-compiler -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH --use_fast_math -Xcompiler="-O2 -Ob2" -DNDEBUG "--generate
  -code=arch=compute_50,code=[sm_50]" "--generate-code=arch=compute_52,code=[sm_52]" "--generate-code=arch=compute_53,code=[sm_53]" "--generate-code=arch=compute_60,co
  de=[sm_60]" "--generate-code=arch=compute_61,code=[sm_61]" "--generate-code=arch=compute_62,code=[sm_62]" "--generate-code=arch=compute_70,code=[sm_70]" "--generate-
  code=arch=compute_72,code=[sm_72]" "--generate-code=arch=compute_75,code=[sm_75]" "--generate-code=arch=compute_80,code=[sm_80]" "--generate-code=arch=compute_86,cod
  e=[sm_86]" "--generate-code=arch=compute_87,code=[sm_87]" "--generate-code=arch=compute_89,code=[sm_89]" "--generate-code=arch=compute_90,code=[compute_90,sm_90]" -X
  compiler=-MD    bitsandbytes.dir\Release\ops.obj bitsandbytes.dir\Release\kernels.obj
  cudart.lib
  cublas.lib
  cusparse.lib
  cublasLt.lib
  nvJitLink.lib
  cudadevrt.lib
  cudart_static.lib
  kernel32.lib
  user32.lib
  gdi32.lib
  winspool.lib
  shell32.lib
  ole32.lib
  oleaut32.lib
  uuid.lib
  comdlg32.lib
  advapi32.lib
  ops.obj
  kernels.obj
  Auto build dll exports
     Criando biblioteca C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes/Release/bitsandbytes_cuda126.lib e objeto C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes/Rel
  ease/bitsandbytes_cuda126.exp
  bitsandbytes.vcxproj -> C:\Users\Admin\Desktop\bitsandbytes\bitsandbytes\bitsandbytes\libbitsandbytes_cuda126.dll
  Building Custom Rule C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes/CMakeLists.txt




```

pip install -e .

```

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///C:/Users/Admin/Desktop/bitsandbytes/bitsandbytes
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      libs: ['libbitsandbytes_cuda126.dll']
      Traceback (most recent call last):
        File "C:\Users\Admin\Desktop\bitsandbytes\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Admin\Desktop\bitsandbytes\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Admin\Desktop\bitsandbytes\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-htdc6r5m\overlay\Lib\site-packages\setuptools\build_meta.py", line 477, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-htdc6r5m\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-htdc6r5m\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-htdc6r5m\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 42, in <module>
        File "<string>", line 17, in read
        File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1415: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


```

### Expected behavior

Install.

**Comment by fabrizio8** [comment]
I'm getting the same error

**Comment by matthewdouglas** [comment]
Thank you for the report @blap! This is now fixed.
