### ISSUE TITLE
CUDA Setup failed despite CUDA being available.

### ISSUE THREAD

**Issue by N1ana7mi** [bitsandbytes-foundation/bitsandbytes#1404]
# This is my terminal output:
(llavatest) nvidia@nvidia-desktop:/home/Storage/workplace$ python -m bitsandbytes
Could not find the bitsandbytes CUDA binary at PosixPath('/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so')
Could not load bitsandbytes native library: /home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 104, in <module>
    lib = get_native_library()
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 91, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
CUDA specs: CUDASpecs(highest_compute_capability=(8, 7), cuda_version_string='114', cuda_version_tuple=(11, 4))
PyTorch settings found: CUDA_VERSION=114, Highest Compute Capability: (8, 7).
Library not found: /home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so. Maybe you need to compile it from source?
If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION`,
for example, `make CUDA_VERSION=113`.

The CUDA version for the compile might depend on your conda install, if using conda.
Inspect CUDA version via `conda list | grep cuda`.
To manually override the PyTorch CUDA version please see: https://github.com/TimDettmers/bitsandbytes/blob/main/docs/source/nonpytorchcuda.mdx
Found duplicate CUDA runtime files (see below).

We select the PyTorch default CUDA runtime, which is 11.4,
but this might mismatch with the CUDA version that is needed for bitsandbytes.
To override this behavior set the `BNB_CUDA_VERSION=<version string, e.g. 122>` environmental variable.

For example, if you want to use the CUDA version 122,
    BNB_CUDA_VERSION=122 python ...

OR set the environmental variable in your .bashrc:
    export BNB_CUDA_VERSION=122

In the case of a manual override, make sure you set LD_LIBRARY_PATH, e.g.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2,
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so.12
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so.12.2.140
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so.12
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so
* Found CUDA runtime at: /usr/local/cuda-12.2/lib64/libcudart.so.12.2.140
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking that the library is importable and CUDA is callable...
Couldn't load the bitsandbytes library, likely due to missing binaries.
Please ensure bitsandbytes is properly installed.

For source installations, compile the binaries with `cmake -DCOMPUTE_BACKEND=cuda -S .`.
See the documentation for more details if needed.

Trying a simple check anyway, but this will likely fail...
Traceback (most recent call last):
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/diagnostics/main.py", line 66, in main
    sanity_check()
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/diagnostics/main.py", line 40, in sanity_check
    adam.step()
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/optim/optimizer.py", line 291, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/optim/optimizer.py", line 521, in update_step
    F.optimizer_update_32bit(
  File "/home/Storage/anaconda3/envs/llavatest/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1624, in optimizer_update_32bit
    optim_func = str2optimizer32bit[optimizer_name][0]
NameError: name 'str2optimizer32bit' is not defined
Above we output some debug information.
Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose
WARNING: Please be sure to sanitize sensitive info from the output before posting it.

# And my cuda in conda environment is shown like this:
(llavatest) nvidia@nvidia-desktop:/home/Storage/workplace$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:08:11_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

**Comment by N1ana7mi** [comment]
And I have compile the bits and bytes in my device and pip it in my conda environment, and I think it compile under the cuda 12.2, does it matter?

**Comment by piedrok** [comment]
I get the same "CUDA Setup failed despite CUDA being available" 

Trying to use InvokeAI. 

Starting invoke ai gives me the following:

`File "/home/piedrok/.invokeai/.venv/lib64/python3.11/site-packages/bitsandbytes/cextension.py", line 109, in
lib = get_native_library()
^^^^^^^^^^^^^^^^^^^^
File "/home/piedrok/.invokeai/.venv/lib64/python3.11/site-packages/bitsandbytes/cextension.py", line 88, in get_native_library
cuda_specs = get_cuda_specs()
^^^^^^^^^^^^^^^^
File "/home/piedrok/.invokeai/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_specs.py", line 39, in get_cuda_specs
cuda_version_string=(get_cuda_version_string()),
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/piedrok/.invokeai/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_specs.py", line 29, in get_cuda_version_string
major, minor = get_cuda_version_tuple()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/piedrok/.invokeai/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_specs.py", line 24, in get_cuda_version_tuple
major, minor = map(int, torch.version.cuda.split("."))
^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
`

python -m bitsandbytes

/usr/bin/python: No module named bitsandbytes

That's clearly wrong as the errors above show. 

What to do?

**Comment by matthewdouglas** [comment]
Hi,

I am closing this issue as it is stale. We've since made improvements to the packaging and setup of the library. 

Please open a new issue for further support as needed.
