### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by shahules786** [bitsandbytes-foundation/bitsandbytes#225]
I'm getting this error while trying to import `bitsandbytes==0.37.2`. 
I am operating from `/home/shahul`

Attached error trace,
```
================================================================================
Traceback (most recent call last):
  File "/home/shahul/Open-Assistant/model/model_training/trainer_rm.py", line 6, in <module>
    import bitsandbytes
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 92, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 371, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 257, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 198, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 193, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 170, in remove_non_existent_dirs
    raise exc
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 166, in remove_non_existent_dirs
    if path.exists():
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/home/shahul/anaconda3/envs/OA/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/jjmachan/python/stubs'
```

**Comment by camperking** [comment]
Your environment paths to cuda are probably wrong.
These commands solved it for me, but you have to check where your cuda lib and bin directories are
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64/
export PATH=$PATH:/usr/local/cuda/bin/
```
