### ISSUE TITLE
UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 

### ISSUE THREAD

**Issue by tiamojames** [bitsandbytes-foundation/bitsandbytes#749]
C:\Users\14908>python -m bitsandbytes
D:\Anaconda\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "D:\Anaconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 35, in find_file_recursive
    out, err = execute_and_return(cmd)
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 30, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 22, in execute_and_return_decoded_std_streams
    return _decode(
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 16, in _decode
    return tuple(
  File "D:\Anaconda\lib\site-packages\bitsandbytes\__main__.py", line 17, in <genexpr>
    to_decode.decode("UTF-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
i dont kown how to solve it at all, help plz

**Comment by stationeros** [comment]
There seems to be an incompatibility of the xFormers  with pytorch. I have been running on M1 mac. Post uninstallation of Xformers and downgrading transformers to 4.3.0 , was able to quantize

**Comment by pechaut78** [comment]
> There seems to be an incompatibility of the xFormers with pytorch. I have been running on M1 mac. Post uninstallation of Xformers and downgrading transformers to 4.30 , was able to quantize

Hi,

Tou were able to run on M1 ? well, I'm surprised, tried, no success. are you using something like:

```
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )
    model = AutoModelForCausalLM.from_pretrained(
                pretrained_model_name_or_path=model_name,
                quantization_config=bnb_config,
                trust_remote_code=True,
                low_cpu_mem_usage=True,
                device_map=gpuDevice,
            )
```

Also, unfortunately 4.30 is quite old now, and does not support many recent models like Mistral for instance, so.. even if working, not really a good solution

Have you got better results with more recent versions of transformer ? I don't

**Comment by stationeros** [comment]
@pechaut78  I was able to run this on M1 , agreed 4.3.0 is a bit old now, agreed mistral is not supported . I will try and publish some benchamrks numbers when I have them ready

**Comment by Titus-von-Koeller** [comment]
Closing due to inactivity, please create a detailed new issue with exact steps to reproduce, in case you're encountering any issue that seems similar to this. Thanks 🤗
