### ISSUE TITLE
Error no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Taigunata** [bitsandbytes-foundation/bitsandbytes#903]
In trying to train my own LoRA model with Kohya i am running into a kernel problem. Kan anyone help or has the same problem?

The full Error-message: 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1500
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 750
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 750
fatal: not a git repository (or any of the parent directories): .git
steps:   0%|                                                                                   | 0/750 [00:00<?, ?it/s]
epoch 1/1
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\dowloads\\kohya_ss-22.3.0\\kohya_ss-22.3.0\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:/LoRA_Modelmaker-Data/Model1/image', '--resolution=512,512', '--output_dir=D:/LoRA_Modelmaker-Data/Model1/model', '--logging_dir=D:/LoRA_Modelmaker-Data/Model1/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=My_LoRA_Model', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=750', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by Taigunata** [comment]
Is solved the Error in changing "AdamW8Bit" to "AdamW" in the optimizer field. At least the training is running now.

**Comment by younesbelkada** [comment]
Maybe Adam8bit is not supported in your device, what hardware are you using?

**Comment by Taigunata** [comment]
I am using a Nvidia GTX 1060 to train LoRA models. Already trained a few with good outputs. So maybe the older hardware is only able to run AdamW optimizer (and other except AdamW8Bit.
