### ISSUE TITLE
BUG, CUDA SETUP,CUDA_VERSION=123_nomatmul

### ISSUE THREAD

**Issue by Flagami** [bitsandbytes-foundation/bitsandbytes#910]
IT'S TRUE MY CUDA VERSION IS 12.3

----------nvcc--version--------
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0

--------------report information-----------------
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=123_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!

Traceback (most recent call last):
  File "finetune_clm_lora.py", line 34, in <module>
    import evaluate
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/evaluate/__init__.py", line 29, in <module>
    from .evaluation_suite import EvaluationSuite
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/evaluate/evaluation_suite/__init__.py", line 10, in <module>
    from ..evaluator import evaluator
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/evaluate/evaluator/__init__.py", line 17, in <module>
    from transformers.pipelines import SUPPORTED_TASKS as SUPPORTED_PIPELINE_TASKS
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 44, in <module>
    from .audio_classification import AudioClassificationPipeline
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/transformers/pipelines/audio_classification.py", line 21, in <module>
    from .base import PIPELINE_INIT_ARGS, Pipeline
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/transformers/pipelines/base.py", line 35, in <module>
    from ..modelcard import ModelCard
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/transformers/modelcard.py", line 48, in <module>
    from .training_args import ParallelMode
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/transformers/training_args.py", line 68, in <module>
    from accelerate.utils import DistributedType
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/storage/.conda/envs/llama2-ch/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by younesbelkada** [comment]
Hi @Flagami 
Have you tried to compile from source: 

```bash
CUDA_VERSION=123 make cuda12x
python setup.py develop
```
