### ISSUE TITLE
libcudart.so | CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by TheFrieber** [bitsandbytes-foundation/bitsandbytes#940]
### System Info

OS: Ubuntu 22.04.3 LTS
--
CPU: AMD Ryzen 5 2600 six-core processor × 12
RAM: 24GB
GPU: NVIDIA RTX 4070 12GB
--
Python Version: 3.10.12
CUDA Version: 12.3
Driver Version: 545.29.06

### Reproduction

-Using Kohya_ss for Lora training-
-Installed with the following guide: https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#linux-pre-requirements
-Executing "echo $CUDA_HOME or echo $LD_LIBRARY_PATH" nothing comes up, i exported LD_LIBRARY_PATH to "usr/lib/wsl/lib/" but the issue stays(as im not using wsl)
```

> -Tried to use install_cuda.sh:
> $ bash install_cuda.sh 118 ~/local/
> basename: missing operand
> Try 'basename --help' for more information.

```

Crashing at "Start training":

```

> The following directories listed in your path were found to be non-existent: {PosixPath('/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
> /home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/2058,unix/thefrieber'), PosixPath('local/thefrieber')}
> The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/4985fdd9_269c_448f_97c2_cd755dc69ff6')}
> The following directories listed in your path were found to be non-existent: {PosixPath('/home/thefrieber/.cache/dotnet_bundle_extract')}
> The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
> The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
> The following directories listed in your path were found to be non-existent: {PosixPath('unix'), PosixPath('path=/run/user/1000/bus,guid=60b9a349e85c0e4bdb4dce346588061a')}
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
> DEBUG: Possible options found for libcudart.so: set()
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Loading binary /home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> libcusparse.so.11: cannot open shared object file: No such file or directory
> CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
> CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
> CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
> CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
> CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
> CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
> CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
> CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
> CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
> Traceback (most recent call last):
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/./train_network.py", line 1012, in <module>
>     trainer.train(args)
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/./train_network.py", line 342, in train
>     optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/library/train_util.py", line 3444, in get_optimizer
>     import bitsandbytes as bnb
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
>     from . import cuda_setup, utils, research
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
>     from . import nn
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
>     from .modules import LinearFP8Mixed, LinearFP8Global
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
>     from bitsandbytes.optim import GlobalOptimManager
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
>     from bitsandbytes.cextension import COMPILED_WITH_CUDA
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
>     raise RuntimeError('''
> RuntimeError: 
>         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>         python -m bitsandbytes
> 
>         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> Traceback (most recent call last):
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
>     args.func(args)
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
>     simple_launcher(args)
>   File "/home/thefrieber/Desktop/AUTO1111/stable-diffusion-webui-1.2.1/lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

```

### Expected behavior

The button "Start training" says it all

**Comment by barasamit** [comment]
solve it?
