### ISSUE TITLE
ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by jianbangzhang** [bitsandbytes-foundation/bitsandbytes#945]
### System Info

win11
transformers==4.29.1
torch==2.0

### Reproduction

    if training_args.do_train:
        train_result = trainer.train()
        trainer.log_metrics("train", train_result.metrics)
        trainer.save_metrics("train", train_result.metrics)
        trainer.save_state()
        trainer.save_model()
        if trainer.is_world_process_zero() and model_args.plot_loss:
            plot_loss(training_args.output_dir, keys=["loss", "eval_loss"])

### Expected behavior

  0%|          | 0/91530 [00:00<?, ?it/s]C:\Users\whu\anaconda3\Lib\site-packages\torch\utils\checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):
  File "C:\MyAICode\training\chatglm-peft\src\train_bash.py", line 21, in <module>
    main()
  File "C:\MyAICode\training\chatglm-peft\src\train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "C:\MyAICode\training\chatglm-peft\src\glmtuner\tuner\sft\workflow.py", line 62, in run_sft
    train_result = trainer.train()
                   ^^^^^^^^^^^^^^^
  File "C:\Users\whu\anaconda3\Lib\site-packages\transformers\trainer.py", line 1664, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whu\anaconda3\Lib\site-packages\transformers\trainer.py", line 1973, in _inner_training_loop
    self.scaler.unscale_(self.optimizer)
  File "C:\Users\whu\anaconda3\Lib\site-packages\torch\cuda\amp\grad_scaler.py", line 307, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(
                                              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\whu\anaconda3\Lib\site-packages\torch\cuda\amp\grad_scaler.py", line 229, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by Titus-von-Koeller** [comment]
closing as stale
