### ISSUE TITLE
Pre-compiled pip package requires `CXXABI_1.3.9` not available on CentOS 7.

### ISSUE THREAD

**Issue by xkszltl** [bitsandbytes-foundation/bitsandbytes#957]
### System Info

CentOS 7 + CUDA 12.3

### Reproduction

Run `scl enable devtoolset-11 rh-python38 'python3 -m bitsandbytes'` on CentOS 7.

```
False

===================================BUG REPORT===================================
/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/opt/rh/devtoolset-11/root/usr/lib/dyninst')}
/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /opt/rh/rh-python38/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst:/usr/local/cuda/lib64:/usr/local/cuda/lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/lib64/qt-3.3/include')}
The following directories listed in your path were found to be non-existent: {PosixPath('/opt/rh/devtoolset-11/root/usr/lib64/pkgconfig')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval `/usr/bin/modulecmd bash $*`\n}')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Loading binary /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so...
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so)
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

You can see `version CXXABI_1.3.9 not found` in log, which would be the root cause of failure when searching for CUDA.

### Expected behavior

CentOS 7 only provides up to CXXABI 1.3.7.
Even when using newer toolchain (gcc-11 in scl), it'll still default to the system's libstdc++.
Pre-compiled package should not depends on CXXABI 1.3.9.

**Comment by matthewdouglas** [comment]
Hi there. CentOS is not supported by our binary wheels as it is [past end of life](https://endoflife.date/centos). 
You may have some luck [building from source](https://huggingface.co/docs/bitsandbytes/main/en/installation#cuda-compile), but we are not able to provide future source compatibility guarantees or support for it.
